# Gerando gráfico de Mês por Temperatura
# Calcula Maximas, Minimas, Medias, Medianas e Modas
getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

database <- read.csv(file="embrapaFine.csv", header=TRUE, sep=";", col.names= c("mes","temperatura","pluviometrico","evaPotencial","armazenHidrico","evaReal","defHidrica","excedHidrico","cidade"), encoding= "UFT8")
database$temperatura <- as.numeric(sub(",",".",database$temperatura))

cat("\n----------------------------------------------\n")
print("Dados Calculados a partir de todas as entradas")
print("=Temperatura")
print("--Menor")
print(min(database$temperatura))
print("--Maior")
print(max(database$temperatura))
print("--Media")
print(mean(database$temperatura))
print("--Mediana")
print(median(database$temperatura))
print("--Moda")
print(getmode(database$temperatura))
cat("\n----------------------------------------------\n")

cat("\n----------------------------------------------\n")
print("Dados Calculados a partir de todas as entradas")
print("Pluviometrico")
print("--Menor")
print(min(database$pluviometrico))
print("--Maior")
print(max(database$pluviometrico))
print("--Media")
print(mean(database$pluviometrico))
print("--Mediana")
print(median(database$pluviometrico))
print("--Moda")
print(getmode(database$pluviometrico))
cat("\n----------------------------------------------\n")

cat("\n----------------------------------------------\n")
print("Dados Calculados a partir de todas as entradas")
print("evaPotencial")
print("--Menor")
print(min(database$evaPotencial))
print("--Maior")
print(max(database$evaPotencial))
print("--Media")
print(mean(database$evaPotencial))
print("--Mediana")
print(median(database$evaPotencial))
print("--Moda")
print(getmode(database$evaPotencial))
cat("\n----------------------------------------------\n")

cat("\n----------------------------------------------\n")
print("Dados Calculados a partir de todas as entradas")
print("armazenHidrico")
print("--Menor")
print(min(database$armazenHidrico))
print("--Maior")
print(max(database$armazenHidrico))
print("--Media")
print(mean(database$armazenHidrico))
print("--Mediana")
print(median(database$armazenHidrico))
print("--Moda")
print(getmode(database$armazenHidrico))
cat("\n----------------------------------------------\n")

cat("\n----------------------------------------------\n")
print("Dados Calculados a partir de todas as entradas")
print("evaReal")
print("--Menor")
print(min(database$evaReal))
print("--Maior")
print(max(database$evaReal))
print("--Media")
print(mean(database$evaReal))
print("--Mediana")
print(median(database$evaReal))
print("--Moda")
print(getmode(database$evaReal))
cat("\n----------------------------------------------\n")

cat("\n----------------------------------------------\n")
print("Dados Calculados a partir de todas as entradas")
print("defHidrica")
print("--Menor")
print(min(database$defHidrica))
print("--Maior")
print(max(database$defHidrica))
print("--Media")
print(mean(database$defHidrica))
print("--Mediana")
print(median(database$defHidrica))
print("--Moda")
print(getmode(database$defHidrica))
cat("\n----------------------------------------------\n")

cat("\n----------------------------------------------\n")
print("Dados Calculados a partir de todas as entradas")
print("defHidrica")
print("--Menor")
print(min(database$excedHidrico))
print("--Maior")
print(max(database$excedHidrico))
print("--Media")
print(mean(database$excedHidrico))
print("--Mediana")
print(median(database$excedHidrico))
print("--Moda")
print(getmode(database$excedHidrico))
cat("\n----------------------------------------------\n")